# Changes here will be overwritten by Copier
_commit: b283b38
_src_path: https://github.com/nialov/nialov-py-template.git
classifier: 'Topic :: Scientific/Engineering :: GIS'
description: Trace data management
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keywords: data analysis spatial geology
package: tracerepo
year: 2021
