---
repos:
  # Check commit messages on commit
  - repo: https://github.com/commitizen-tools/commitizen
    # Specify tag
    rev: v2.17.13
    hooks:
      - id: commitizen
        stages: [commit-msg]
